### ISSUE TITLE
version command panics

### ISSUE THREAD

**Issue by aaronjheng** [raphaelreyna/oneshot#36]
**Describe the bug**
As title

**To Reproduce**
1. Run 'oneshot version'

**Expected behavior**
Version output shows up.

**Output and error messages**
```
panic: interface conversion: pflag.Value is *pflag.stringValue, not *flagargs.OutputFormat [recovered]
	panic: interface conversion: pflag.Value is *pflag.stringValue, not *flagargs.OutputFormat

goroutine 1 [running]:
main.main.func1()
	/Users/rr/Code/ForestNode/oneshot/v2/cmd/main.go:45 +0x73
panic({0x1893aa0?, 0xc0001d1a70?})
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/panic.go:914 +0x21f
github.com/forestnode-io/oneshot/v2/pkg/commands/root.subCommands.(*Cmd).Cobra.func1(0x1b08bc0?, {0xc0003a6120?, 0x0?, 0x213e940?})
	/Users/rr/Code/ForestNode/oneshot/v2/pkg/commands/version/cobra.go:30 +0x485
github.com/forestnode-io/oneshot/v2/pkg/commands/root.(*rootCommand).setSubCommands.func2(0xc0003a4300, {0x213e940, 0x0, 0x0})
	/Users/rr/Code/ForestNode/oneshot/v2/pkg/commands/root/entry.go:128 +0x6f
github.com/spf13/cobra.(*Command).execute(0xc0003a4300, {0x213e940, 0x0, 0x0})
	/Users/rr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0xc000290000)
	/Users/rr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/Users/rr/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:985
github.com/forestnode-io/oneshot/v2/pkg/commands/root.ExecuteContext({0x1b08d80, 0xc0001caac0})
	/Users/rr/Code/ForestNode/oneshot/v2/pkg/commands/root/entry.go:81 +0x698
main.main()
	/Users/rr/Code/ForestNode/oneshot/v2/cmd/main.go:77 +0x2ed
```

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Version: 2.0.0

**Additional context**
None

**Comment by raphaelreyna** [comment]
Oof that's embarrassing, good catch though!
This is now fixed in the latest release: [v2.0.1](https://github.com/forestnode-io/oneshot/releases/tag/v2.0.1).
Looks like this slipped by the tests, but I fixed that as well.
I also added the `-trimpath` flag to builds to clean up file names on panics.
